model:
  cldm:
    target: terediff.model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  swinir:
    target: terediff.model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

  diffusion:
    target: terediff.model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000
      zero_snr: True
      parameterization: v


dataset:
  val_dataset_name: RealText
  gt_img_path: /data/text_restoration/real_benchmark_full/HQ
  lq_img_path: /data/text_restoration/real_benchmark_full/LQ
  gt_ann_path: /data/text_restoration/real_benchmark_full/real_benchmark_dataset.json



train:
  sd_path: ./weights/sd2.1-base-zsnr-laionaes5.ckpt       
  swinir_path: ./weights/realesrgan_s4_swinir_100k.pth
  resume: ./weights/DiffBIR_v2.1.pt


model_args:
  model_H: 512 
  model_W: 512 


exp_args:
  mode: VAL
  model_name: terediff_stage3
  testr_ckpt_dir: 
  resume_ckpt_dir: model_ckpts/terediff_stage3.pt  # to use our ckpt set it to /PATH/TO/terediff_stage3.pt
  # resume_ckpt_dir: model_ckpts/jihye_weight/0020000.pt
  # resume_ckpt_dir: model_ckpts/jihye/stage1/0056000_real.pt
  inf_sample_step: 50
  save_result_img: True
  save_result_prompt: True
  # save_val_img_dir: /home/cvlab08/projects/data/jinlovespho/iclr26/tair_extension/realtext/terediff_stage3
  # save_val_img_dir: /data/jinlovespho/iclr2026/tair_extension/realtext/terediff_stage3
  # save_val_img_dir: /home/cvlab08/projects/data/jinlovespho/iclr26/tair_rebuttal/no_prompt_training/terediff_stage3/realtext
  # save_val_img_dir: /media/dataset1/jinlovespho/iclr26/DiT4SR/results/realtext/tair_stage3_tsprompt
  # save_val_img_dir: /media/dataset1/jinlovespho/iclr26/DiT4SR/results/realtext/tair_stage1_llavaprompt
  save_val_img_dir:



prompter_args:
  prompt_style: TAG   # choose from [CAPTION, TAG] for prompting styles
  use_gt_prompt: False
  use_ts_prompt: True
  use_edit_prompt: False
  editting_text: 
  use_vlm_prompt: False
  use_null_prompt: False
  use_llava_prompt: False
  llava_prompt_dir: /media/dataset2/text_restoration/tair_published/real_text/dit4sr/data/llava13b_lq_prompt.json
  use_qwen_prompt: False
  qwen_prompt_dir: /media/dataset1/jinlovespho/iclr26/DiT4SR/results/satext/lv3/vlm_ocr_result/qwen/7b.json


vlm_args:
  # vlm_device: "cuda:5"
  vlm_name: qwenVL3B
  vlm_input_img: RESTORE  # [choose from LQ, CLEAN, RESTORE]
  inf_vlm_step: 2
  vlm_text_correction: False
  

log_args:
  log_tool: wandba
  wandb_key: e32eed0c2509bf898b850b0065ab62345005fb73
  wandb_proj_name: TAIR_EXTENSION
  user: pho_rebuttal
  server: 18
  gpu: 6

vis_args:
  vis_attn_map: False
  # attn_map_save_dir: ./vis/camap/realtext/terediff_stage3_gtprompt_v2
  # attn_map_save_dir: ./vis/camap/realtext/terediff_stage1_gtprompt_v3
  attn_map_save_dir: ./vis/camap/realtext/terediff_stage3_gtprompt_v3
  # vis_diff_timesteps: [999, 917, 836, 754, 673, 591, 510, 428, 347, 265, 183, 102, 20]
  vis_diff_timesteps: [999, 754, 510, 265, 20]
  avg_attn_layers: True
  all_attn_layers: True
